
export const helpSupportFormData = [
  {
    type: 'SELECT_FIELD',
    label: 'Content Type',
    validationType: 'general',
    id: 'contenttype',
    name: 'contenttype',
    placeholder: 'Select Content Type',
    required: true,
    options: [
      {
        label: 'FAQ',
        value: 'faq',
      },
      {
        label: 'Guidelines',
        value: 'guidelines',
      },
      {
        label: 'Contact Information',
        value: 'contact',
      },
      {
        label: 'Terms of Service',
        value: 'terms',
      },
      {
        label: 'Privacy Policy',
        value: 'privacy',
      },
      {
        label: 'General Information',
        value: 'general',
      },
    ],
  },
  {
    type: 'TEXT_FIELD',
    label: 'Title',
    validationType: 'general',
    attributeType: 'text',
    id: 'title',
    name: 'title',
    placeholder: 'Enter content title',
    required: true,
  },
  {
    type: 'TEXTAREA_FIELD',
    label: 'Content',
    validationType: 'general',
    id: 'content',
    name: 'content',
    placeholder: 'Enter help and support content...',
    required: true,
    rows: 8,
  },
  {
    type: 'SELECT_FIELD',
    label: 'Status',
    validationType: 'general',
    id: 'status',
    name: 'status',
    placeholder: 'Select Status',
    required: true,
    options: [
      {
        label: 'Active',
        value: 'active',
      },
      {
        label: 'Inactive',
        value: 'inactive',
      }, 
    ],
  },
  // {
  //   type: 'TEXT_FIELD',
  //   label: 'Display Order',
  //   validationType: 'number',
  //   id: 'display_order',
  //   name: 'display_order',
  //   placeholder: 'Enter display order (1 shows first)',
  //   required: true,
  //   min: 1,
  //   max: 100,
  // },
  {
    type: 'TEXT_FIELD',
    label: 'Contact Email',
    validationType: 'email',
    attributeType: 'email',
    id: 'email',
    name: 'email',
    placeholder: 'Enter support email address',
    required: false,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Contact Phone',
    validationType: 'mobile',
    attributeType: 'text',
    id: 'mobile',
    name: 'mobile',
    placeholder: 'Enter support phone number',
    required: false,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Support Hours',
    validationType: 'general',
    attributeType: 'text',
    id: 'supporthours',
    name: 'supporthours',
    placeholder: 'e.g., Mon-Fri 9AM-6PM',
    required: false,
  },
];
