export const itemTableData = [
    {
        id: 1,
        item_image: '',
        item_code: 'IT001',
        item_name: 'Paint - 1',
        hsn_code: '00121',
        sku_code: '14510',
        brand_title: 'Asian Paints',
        category_title: 'Paints',
        unit_title: 'Box',
        Current_stock_qty: '1',
        minimum_stock_qty: '1',
        purchase_price: '100',
        sales_price: '200',
        tax_details: 'GST - 18%',
        tax_type: 'Exclusive',
        created_at: '2024-11-07T12:45:40.000Z',
        updated_at: '2024-11-07T12:45:40.000Z',
        user_created: {
            fullname: 'admin'
        },
        user_updated: null
    },
];

export const itemFormData = [
    {
        type: 'TEXT_FIELD',
        label: 'Item Name',
        validationType: 'general',
        attributeType: 'text',
        id: 'item_name',
        name: 'item_name',
        placeholder: 'Enter Your Item Name',
        required: true,
    },
    {
        type: 'SELECT_FIELD_FILTER',
        label: 'Brand',
        validationType: 'general',
        id: 'brand_id',
        name: 'brand_id',
        placeholder: 'Select Your Brand',
        required: true,
        options: [{
            label: 'Brand - 1',
            value: '1',
        }, {
            label: 'Brand - 2',
            value: '2',
        }]
    },
    {
        type: 'SELECT_FIELD_FILTER',
        label: 'Category',
        validationType: 'general',
        id: 'category_id',
        name: 'category_id',
        placeholder: 'Select Your Category',
        required: true,
        options: [{
            label: 'Category - 1',
            value: '1',
        }, {
            label: 'Category - 2',
            value: '2',
        }]
    },
    {
        type: 'SELECT_FIELD_FILTER',
        label: 'Unit',
        validationType: 'general',
        id: 'unit_id',
        name: 'unit_id',
        placeholder: 'Select Your Unit',
        required: true,
        options: [{
            label: 'Unit - 1',
            value: '1',
        }, {
            label: 'Unit - 2',
            value: '2',
        }]
    },
    {
        type: 'TEXT_FIELD',
        label: 'SKU',
        validationType: 'general',
        attributeType: 'text',
        id: 'sku_code',
        name: 'sku_code',
        placeholder: 'Enter Your sku code',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'HSN',
        validationType: 'general',
        attributeType: 'text',
        id: 'hsn_code',
        name: 'hsn_code',
        placeholder: 'Enter Your hsn code',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'HSN',
        validationType: 'general',
        attributeType: 'text',
        id: 'hsn_code',
        name: 'hsn_code',
        placeholder: 'Enter Your hsn code',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'Minimum Qty',
        validationType: 'general',
        attributeType: 'text',
        id: 'minimum_stock_qty',
        name: 'minimum_stock_qty',
        placeholder: 'Enter Your Minimum Qty',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'Lot Number',
        validationType: 'general',
        attributeType: 'text',
        id: 'lot_number',
        name: 'lot_number',
        placeholder: 'Enter Your Lot Number',
        required: true,
    },
    {
        type: 'TEXTAREA_FIELD',
        label: 'Description',
        validationType: 'general',
        id: 'description',
        name: 'description',
        placeholder: 'Enter Your description',
        required: true,
    },
    {
        type: 'FILE_UPLOAD_FIELD',
        label: 'Item Image',
        validationType: 'image',
        id: 'item_image',
        name: 'item_image',
        placeholder: 'Select Item Image',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'Purchase Price',
        validationType: 'general',
        attributeType: 'text',
        id: 'purchase_price',
        name: 'purchase_price',
        placeholder: 'Enter Your Purchase Price',
        required: true,
    },
    {
        type: 'SELECT_FIELD_FILTER',
        label: 'Purchase Tax',
        validationType: 'general',
        id: 'purchase_tax_id',
        name: 'purchase_tax_id',
        placeholder: 'Select Your Purchase Tax',
        required: true,
        options: [{
            label: 'GST - 18',
            value: '1',
        }, {
            label: 'CGST - 18',
            value: '2',
        }]
    },
    {
        type: 'SELECT_FIELD',
        label: 'Purchase Tax Type',
        validationType: 'general',
        id: 'purchase_tax_type',
        name: 'purchase_tax_type',
        placeholder: 'Select Your Purchase Tax Type',
        required: true,
        options: [{
            label: 'Inclusive',
            value: '1',
        }, {
            label: 'Exclusive',
            value: '2',
        }]
    },
    {
        type: 'TEXT_FIELD',
        label: 'Final Purchase Price',
        validationType: 'general',
        attributeType: 'text',
        id: 'purchase_price',
        name: 'purchase_price',
        placeholder: 'Enter Your Purchase Price',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'Sales Price',
        validationType: 'general',
        attributeType: 'text',
        id: 'sales_price',
        name: 'sales_price',
        placeholder: 'Enter Your Sales Price',
        required: true,
    },
    {
        type: 'SELECT_FIELD_FILTER',
        label: 'Sales Tax',
        validationType: 'general',
        id: 'sales_tax_id',
        name: 'sales_tax_id',
        placeholder: 'Select Your Sales Tax',
        required: true,
        options: [{
            label: 'GST - 18',
            value: '1',
        }, {
            label: 'CGST - 18',
            value: '2',
        }]
    },
    {
        type: 'SELECT_FIELD',
        label: 'Sales Tax Type',
        validationType: 'general',
        id: 'sales_tax_type',
        name: 'sales_tax_type',
        placeholder: 'Select Your Sales Tax Type',
        required: true,
        options: [{
            label: 'Inclusive',
            value: '1',
        }, {
            label: 'Exclusive',
            value: '2',
        }]
    },
    {
        type: 'TEXT_FIELD',
        label: 'Final Sales Price',
        validationType: 'general',
        attributeType: 'text',
        id: 'sales_price',
        name: 'sales_price',
        placeholder: 'Enter Your Sales Price',
        required: true,
    },
    {
        type: 'SELECT_FIELD',
        label: 'Discount Type',
        validationType: 'general',
        id: 'discount_type',
        name: 'discount_type',
        placeholder: 'Select Your Discount Type',
        required: true,
        options: [{
            label: 'Percentage(%)',
            value: '1',
        }, {
            label: 'Fixed(₹)',
            value: '2',
        }]
    },
    {
        type: 'TEXT_FIELD',
        label: 'Discount',
        validationType: 'general',
        attributeType: 'text',
        id: 'discount',
        name: 'discount',
        placeholder: 'Enter Your Discount',
        required: true,
    },
];

export const itemData = [
    {
      id: '1',
      item_no: 'TI001',
      item_name: 'HM Roll Vergin',
      qty: 1,
      rate: '100.00',
      unit_id: 1,
      discount: '10',
      discount_type: 'Fixed',
    },
    {
      id: '2',
      item_no: 'TI002',
      item_name: 'LD Roll',
      qty: 1,
      rate: '112.00',
      unit_id: 1,
      discount: '10',
      discount_type: 'Percentage',
    },
    {
      id: '3',
      item_no: 'TI003',
      item_name: 'LD Printing Bag',
      qty: 0,
      rate: '100.00',
      unit_id: 1,
      discount: '10',
      discount_type: 'Fixed',
    },
  ];