export const sampleFormData = [
    {
      type: 'TEXT_FIELD',
      label: 'Brand title',
      validationType: 'general',
      attributeType: 'text',
      id: 'brand_title',
      name: 'brand_title',
      placeholder: 'Enter Your Brand title',
      required: true,
    },
    {
      type: 'SELECT_FIELD',
      label: 'District Name',
      validationType: 'general',
      id: 'district_name',
      name: 'district_name',
      placeholder: 'Select Your District Name',
      required: true,
      options: [{
        label: 'Coimbatore',
        value: '1',
      }, {
        label: 'Chennai',
        value: '2',
      }]
    },
    {
      type: 'DATE_FIELD',
      label: 'Date',
      validationType: 'general',
      id: 'date',
      name: 'date',
      placeholder: 'Select Your Date',
      required: true,
    },
    {
      type: 'TEXTAREA_FIELD',
      label: 'Location Link',
      validationType: 'general',
      id: 'location_link',
      name: 'location_link',
      placeholder: 'Enter Your Location Link',
      required: true,
    },
    {
      type: 'PRIVATE_FIELD',
      label: 'Password',
      validationType: 'general',
      id: 'password',
      name: 'password',
      placeholder: 'Enter Your Password',
      required: true,
    },
    {
      type: 'TEXT_FIELD',
      label: 'Email',
      validationType: 'email',
      attributeType: 'email',
      id: 'email',
      name: 'email',
      placeholder: 'Enter Your Email',
      required: true,
    },
    {
      type: 'TEXT_FIELD',
      label: 'Mobile Number',
      validationType: 'mobile',
      attributeType: 'number',
      id: 'mobile_number',
      name: 'mobile_number',
      placeholder: 'Enter Your Mobile Number',
      required: true,
    },
    {
      type: 'FILE_UPLOAD_FIELD',
      label: 'Banner Image',
      validationType: 'image',
      id: 'asset',
      name: 'asset',
      placeholder: 'Enter Your Image',
      required: true,
    },
  ];