export const scrapProductFormData = [
    {
        type: 'TEXT_FIELD',
        label: 'Product Name',
        validationType: 'general',
        attributeType: 'text',
        id: 'product_name',
        name: 'product_name',
        placeholder: 'Enter product name',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'Description',
        validationType: 'general',
        attributeType: 'text',
        id: 'description',
        name: 'description',
        placeholder: 'Enter description',
        required: false,
    },
    {
        type: 'NUMBER_FIELD',
        label: 'Total Quantity',
        validationType: 'general',
        attributeType: 'number',
        id: 'total_quantity',
        name: 'total_quantity',
        placeholder: 'Enter quantity',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'Unit',
        validationType: 'general',
        attributeType: 'text',
        id: 'unit',
        name: 'unit',
        placeholder: 'Enter unit (e.g., kg, pieces)',
        required: true,
    },
    {
        type: 'SELECT_FIELD',
        label: 'Status',
        validationType: 'general',
        id: 'status',
        name: 'status',
        required: true,
        options: [
            { label: 'Active', value: true },
            { label: 'Inactive', value: false },
        ],
    },
];
