export const scrapSaleFormData = [
    {
        type: 'SELECT_FIELD',
        label: 'Scrap Product',
        validationType: 'general',
        id: 'scrap_product_id',
        name: 'scrap_product_id',
        required: true,
        options: [], // To be populated dynamically
    },
    {
        type: 'TEXT_FIELD',
        label: 'Buyer Name',
        validationType: 'general',
        attributeType: 'text',
        id: 'buyer_name',
        name: 'buyer_name',
        placeholder: 'Enter buyer name',
        required: true,
    },
    {
        type: 'NUMBER_FIELD',
        label: 'Quantity Sold',
        validationType: 'general',
        attributeType: 'number',
        id: 'quantity',
        name: 'quantity',
        placeholder: 'Enter quantity sold',
        required: true,
    },
    {
        type: 'NUMBER_FIELD',
        label: 'Price Per Unit',
        validationType: 'general',
        attributeType: 'number',
        id: 'price_per_unit',
        name: 'price_per_unit',
        placeholder: 'Enter price per unit',
        required: true,
    },
    {
        type: 'TEXT_FIELD',
        label: 'Sale Date',
        validationType: 'general',
        attributeType: 'date',
        id: 'sale_date',
        name: 'sale_date',
        required: true,
    },
];
