export const supplierTableData = [
  {
    id: 1,
    supplier_name: 'Flipcod-office',
    contact_person_name: 'Naveen',
    mobile_number: '9876543210',
    alt_mobile_number: '9876543210',
    address: 'Karur',
    district: 'Karur',
    state: 'Karur',
    country: 'Karur',
    description: 'Karur',
    gst_no: '9999999999999',
    created_at: '2024-11-07T12:45:40.000Z',
    updated_at: '2024-11-07T12:45:40.000Z',
    user_created: {
      fullname: 'admin'
    },
    user_updated: null
  },
];

export const supplierData = [
  {
    id: '1',
    supplier_name: 'Marvel Fabrics',
    contact_person_name: 'Mr. Dhinesh',
    phone_number: '9994844666',
    email: 'info@marvelfabrics.com',
    address_1: 'No.2-B, Sengunthapuram,',
    address_2: '12th Cross Strret',
    district: 'Karur',
    state: 'Tamilnadu',
    country: 'India',
    gst: '33AAYFM6520D1Z8',
    created_at: '2024-11-07T12:45:40.000Z',
    updated_at: '2024-11-07T12:45:40.000Z',
    user_created: {
      fullname: 'admin'
    },
    user_updated: null
  },
  {
    id: '2',
    supplier_name: 'Aishwarya Poly Mers',
    contact_person_name: 'Mr.Karthik',
    phone_number: '9789491484',
    email: 'pushparajttt@gmail.com',
    address_1: '217 A Esantham Road,Thirumanilaiyur,',
    address_2: 'Karur-639003',
    district: 'Karur',
    state: 'Tamilnadu',
    country: 'India',
    gst: '33BUCPK8449Q1ZY',
    created_at: '2024-11-07T12:45:40.000Z',
    updated_at: '2024-11-07T12:45:40.000Z',
    user_created: {
      fullname: 'admin'
    },
    user_updated: null
  },
  {
    id: '3',
    supplier_name: 'P.R. Traders',
    contact_person_name: 'Sathish kumar',
    phone_number: '9791422780',
    email: 'prtrader2005@gmail.com',
    address_1: 'No.5,Vijay Nagar,',
    address_2: '12th Cross Strret',
    district: 'Karur',
    state: 'Tamilnadu',
    country: 'India',
    gst: '33AASPP6990J1ZG',
    created_at: '2024-11-07T12:45:40.000Z',
    updated_at: '2024-11-07T12:45:40.000Z',
    user_created: {
      fullname: 'admin'
    },
    user_updated: null
  },
];

export const supplierFormData = [
  {
    type: 'TEXT_FIELD',
    label: 'Supplier Name',
    validationType: 'general',
    attributeType: 'text',
    id: 'supplier_name',
    name: 'supplier_name',
    placeholder: 'Enter Your Supplier Name',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Contact Person Name',
    validationType: 'general',
    attributeType: 'text',
    id: 'contact_person_name',
    name: 'contact_person_name',
    placeholder: 'Enter Your Contact Person Name',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Mobile Number',
    validationType: 'mobile',
    attributeType: 'number',
    id: 'mobile_number',
    name: 'mobile_number',
    placeholder: 'Enter Your Mobile Number',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Alternate Mobile Number',
    validationType: 'mobile',
    attributeType: 'number',
    id: 'alt_mobile_number',
    name: 'alt_mobile_number',
    placeholder: 'Enter Your Alternate Mobile Number',
    required: false,
  },
  {
    type: 'TEXT_FIELD',
    label: 'GST No',
    validationType: 'general',
    attributeType: 'text',
    id: 'gst_no',
    name: 'gst_no',
    placeholder: 'Enter Your Gst No',
    required: true,
  },
  {
    type: 'TEXTAREA_FIELD',
    label: 'Address',
    validationType: 'general',
    attributeType: 'text',
    id: 'address',
    name: 'address',
    placeholder: 'Enter Your Address',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'District',
    validationType: 'general',
    attributeType: 'text',
    id: 'district',
    name: 'district',
    placeholder: 'Enter Your District',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'State',
    validationType: 'general',
    attributeType: 'text',
    id: 'state',
    name: 'state',
    placeholder: 'Enter Your State',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Country',
    validationType: 'general',
    attributeType: 'text',
    id: 'country',
    name: 'country',
    placeholder: 'Enter Your Country',
    required: true,
  },
  {
    type: 'TEXTAREA_FIELD',
    label: 'Description',
    validationType: 'general',
    attributeType: 'text',
    id: 'description',
    name: 'description',
    placeholder: 'Enter Your Description',
    required: false,
  },
];