export const testimonialFormData = [
  {
    type: 'TEXT_FIELD',
    label: 'Client Name',
    validationType: 'general',
    attributeType: 'text',
    id: 'clientname',
    name: 'clientname',
    placeholder: 'Enter client name',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Client Profession',
    validationType: 'general',
    attributeType: 'text',
    id: 'clientprofession',
    name: 'clientprofession',
    placeholder: 'Enter client profession or company',
    required: false,
  },
  {
    type: 'TEXTAREA_FIELD',
    label: 'Testimonial Content',
    validationType: 'general',
    id: 'testimonialcontent',
    name: 'testimonialcontent',
    placeholder: 'Enter client testimonial...',
    required: true,
    rows: 6,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Rating (1-5)',
    validationType: 'number',
    attributeType: 'number',
    id: 'rating',
    name: 'rating',
    placeholder: 'Enter rating from 1 to 5',
    required: true,
    min: 1,
    max: 5,
  },
  {
    type: 'SELECT_FIELD',
    label: 'Status',
    validationType: 'general',
    id: 'status',
    name: 'status',
    placeholder: 'Select Status',
    required: true,
    options: [
      {
        label: 'Active',
        value: 'active',
      },
      {
        label: 'Inactive',
        value: 'inactive',
      }, 
    ]
  },
  // {
  //   type: 'NUMBER_FIELD',
  //   label: 'Display Order',
  //   validationType: 'number',
  //   id: 'display_order',
  //   name: 'display_order',
  //   placeholder: 'Enter display order (1 shows first)',
  //   required: true,
  //   min: 1,
  //   max: 100,
  // },
  {
    type: 'FILE_UPLOAD_FIELD',
    label: 'Client Photo',
    validationType: 'image',
    id: 'clientimage',
    name: 'clientimage',
    placeholder: 'Upload client photo',
    required: false,
    preview: true,
  },
  // {
  //   type: 'DATE_FIELD',
  //   label: 'Testimonial Date',
  //   validationType: 'date',
  //   id: 'testimonial_date',
  //   name: 'testimonial_date',
  //   placeholder: 'Select testimonial date',
  //   required: true,
  // }
];