export const workerTableData = [
  {
    id: 1,
    worker_name: 'Naveen',
    mobile_number: '9876543210',
    alt_mobile_number: '9876543210',
    address: 'Karur',
    district: 'Karur',
    state: 'Karur',
    country: 'Karur',
    description: '',
    aadhar_no: '9999999999999',
    worker_type: 'Helper worker',
    created_at: '2024-11-07T12:45:40.000Z',
    updated_at: '2024-11-07T12:45:40.000Z',
    user_created: {
      fullname: 'admin'
    },
    user_updated: null
  },
];

export const workerFormData = [
  {
    type: 'TEXT_FIELD',
    label: 'Worker Name',
    validationType: 'general',
    attributeType: 'text',
    id: 'worker_name',
    name: 'worker_name',
    placeholder: 'Enter Your Worker Name',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Mobile Number',
    validationType: 'mobile',
    attributeType: 'number',
    id: 'mobile_number',
    name: 'mobile_number',
    placeholder: 'Enter Your Mobile Number',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Alternate Mobile Number',
    validationType: 'mobile',
    attributeType: 'number',
    id: 'alt_mobile_number',
    name: 'alt_mobile_number',
    placeholder: 'Enter Your Alternate Mobile Number',
    required: false,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Aadhar No',
    validationType: 'general',
    attributeType: 'text',
    id: 'aadhar_no',
    name: 'aadhar_no',
    placeholder: 'Enter Your Aadhar No',
    required: false,
  },
  {
    type: 'SELECT_FIELD',
    label: 'Worker Type',
    validationType: 'general',
    id: 'worker_type',
    name: 'worker_type',
    placeholder: 'Select Your Worker Type',
    required: true,
    options: [
      {
        label: 'Helper worker',
        value: '1',
      },
    ]
  },
  {
    type: 'TEXTAREA_FIELD',
    label: 'Address',
    validationType: 'general',
    attributeType: 'text',
    id: 'address',
    name: 'address',
    placeholder: 'Enter Your Address',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'District',
    validationType: 'general',
    attributeType: 'text',
    id: 'district',
    name: 'district',
    placeholder: 'Enter Your District',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'State',
    validationType: 'general',
    attributeType: 'text',
    id: 'state',
    name: 'state',
    placeholder: 'Enter Your State',
    required: true,
  },
  {
    type: 'TEXT_FIELD',
    label: 'Country',
    validationType: 'general',
    attributeType: 'text',
    id: 'country',
    name: 'country',
    placeholder: 'Enter Your Country',
    required: true,
  },
  {
    type: 'TEXTAREA_FIELD',
    label: 'Description',
    validationType: 'general',
    attributeType: 'text',
    id: 'description',
    name: 'description',
    placeholder: 'Enter Your Description',
    required: false,
  },
];